# a_tensor_initialization.py

In [15]:
import torch

In [16]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')

* torch.Tensor: PyTorch에서 제공하는 tensor 객체를 생성하는 함수

    - 입력 데이터로 리스트, 배열, 다른 tensor 등 다양한 형태의 데이터를 받을 수 있음

    - 데이터를 지정하지 않고 크기만 입력할 수 있음 (이 경우, 메모리가 초기화되지 않은 임의의 값으로 채워지게 됨)
        + torch.Tensor(2, 3) : 크기가 2 x 3인 tensor, 초기화되지 않은 값 포함

    - 기본적으로 float32형 데이터로 초기화됨
        + 정수형이나 다른 데이터 타입의 tensor를 원할 경우, torch.tensor() 함수에서 명시적으로 dtype을 설정하는 것이 좋음
    
    - tensor를 특정 device(cpu or gpu)에 할당할 수 있음 (기본적으로 cpu에 tensor를 생성함)

    - 예시
        + torch.Tensor([1, 2, 3]) : 1D tensor 생성
        + torch.Tensor([1, 2], [3, 4]) : 2D tensor 생성


In [17]:
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


- t1.dtype: tensor의 data type을 출력함
    + 기본적으로 float32로 초기화됨

- t1.device: tensor가 저장된 device를 출력함 -> cpu or gpu

- t1.requires_grad: tensor의 자동 미분(gradient)를 추적할지를 나타냄
    + 기본적으로 False로 설정되어 있음
        + 이는 tensor가 backprop 과정에서 gradient를 추적하지 않음을 의미함
        + 학습 가능한 파라미터가 아니기 때문에 gradient를 계산할 필요가 없다는 의미

- t1.size: tensor의 크기를 반환
    + tensor의 각 차원별 크기를 torch.Size 객체로 반환
        + 예시 속 tensor는 [1, 2, 3]이라는 3개의 요소를 가진 1D tensor이므로 크기는 [3]

- t1.shape: tensor의 shape를 나타냄
    + size()와 동일한 정보를 반환함

In [18]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')

- torch.tensor: 주어진 데이터를 기반으로 tensor를 생성하는 함수
    + 기본 사용법 : 
        <code>
        torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
        </code>
        + data, type, device, requires_grad는 위의 내용과 동일함
        + pin_memory: 고정된 메모리를 사용하여 GPU와의 데이터 전송을 빠르게 할 수 있음(주로 GPU 관련 연산에서 사용됨)

- torch.Tensor와 torch.tensor의 차이
    + torch.Tensor: 기본적으로 torch.FloatTensor 반환, data type을 명시적으로 지정하지 않으면 float32가 기본값임
    + torch.tensor: 입력에 따라 data type을 유추하거나 명시적으로 type을 지정할 수 있음

In [19]:
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


In [20]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
                                     # torch.size([]): tensor의 차원이 없음 == schalar(0차원 tensor)
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
                                     # 1개의 요소를 가지고 있는 1차원 tensor
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
                                     # 5개의 요소를 가지고 있는 1차원 tensor
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
                                               # 5개의 행과 1개의 열로 이루어진 2차원 tensor
print(a4.shape, a4.ndim)

a5 = torch.tensor([                  # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
                                     # 3개의 행과 2개의 열로 이루어진 2차원 tensor
print(a5.shape, a5.ndim)

a6 = torch.tensor([                  # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
                                     # 3개의 블록이 있고, 각 블록은 2x1 크기를 가짐
print(a6.shape, a6.ndim)

a7 = torch.tensor([                  # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
                                     # 3개의 블록이 있고, 각 블록은 1x2x1 크기를 가짐
print(a7.shape, a7.ndim)

a8 = torch.tensor([                  # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
                                     # 3개의 블록이 있고, 각 블록은 1x2x3 크기를 가짐
print(a8.shape, a8.ndim)


a9 = torch.tensor([                  # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
                                     # 3개의 블록이 있고, 각 블록은 1x2x3x1 크기를 가짐
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
                                     # 4개의 행과 5개의 열로 이루어진 2차원 tensor
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
                                    # 4개의 블록이 있고, 각 블록은 1x5 크기를 가짐
print(a10.shape, a10.ndim)

a11 = torch.tensor([                # ValueError: expected sequence of length 3 at dim 3 (got 2) => 크기가 일관되지 않음
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])


torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

# b_tenser_initialization_copy.py

In [21]:
import torch
import numpy as np

In [22]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


- python 리스트로부터의 tensor 생성
    - torch.Tensor
        - 기본적으로 data type이 float32형이기 때문에 t1의 요소 값도 float32형으로 저장
        - 원본 리스트와 메모리 공유하지 않음
            - 리스트 l1의 값을 수정해도 tensor t1에는 영향을 미치지 않음
    - torch.tensor
        - 리스트 l2의 요소 값에 대한 data type을 유추해서 t2의 요소 값의 data type을 int형으로 저장
        - 원본 리스트와 메모리 공유하지 않음
            - 리스트 l2의 값을 수정해도 tensor t2에는 영향을 미치지 않음
    - torch.as_tensor
        - 가능한 경우 원본 데이터를 공유하려는 특성 있음
        - 하지만 python의 일반적인 리스트는 메모리에서 tensor와 직접 공유되지 않음
            - 리스트 l3의 값을 수정해도 tensor t3에는 영향을 미치지 않음

- Numpy 배열로부터 tensor 생성
    - torch.Tensor
        - Numpy 배열 l4와 메모리를 공유하지 않음
            - 배열 l4의 값을 수정해도 tensor t4에는 영향을 미치지 않음
    - torch.tensor
        - Numpy 배열 l5와 메모리를 공유하지 않음
            - 배열 l5의 값을 수정해도 tensor t5에는 영향을 미치지 않음
    - torch.as_tensor
        - **Numpy 배열과 메모리를 공유함**
            - Numpy 배열 l6의 데이터를 그대로 가져와 tensor를 생성하며, 데이터도 공유함
            - 배열 l6의 값을 수정하면 tenser t6의 값도 함꼐 변경됨

# c_tensor_initialization_constant_values.py

In [23]:
import torch

In [24]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([3.2988e+11, 4.5744e-41, 3.8022e-34, 0.0000e+00])
tensor([3.2988e+11, 4.5744e-41, 3.2988e+11, 4.5744e-41])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


<pre>
<code>
torch.ones(size)
</code>
: 모든 값이 1인 tensor 생성
ex. torch.ones(size=(5,)): 길이가 5인 1차원 tensor 생성

<code>
torch.ones_like(input)
</code>
: input과 동일한 크기 및 데이터 타입을 가진 tensor를 생성하고, 모든 값을 1.0으로 초기화(input과는 다른 새로운 tensor임)
</pre>

<pre>
<code>
torch.zeros(size)
</code>
: 모든 값이 0인 tensor 생성
ex. torch.zeros(size=(6,)): 길이가 6인 1차원 tensor 생성

<code>
torch.zeros_like(input)
</code>
: input과 동일한 크기 및 데이터 타입을 가진 tensor를 생성하고, 모든 값을 0.0으로 초기화(input과는 다른 새로운 tensor임)
</pre>

<pre>
<code>
torch.empty(size)
</code>
: 초기화되지 않은 텐서를 생성(초기값이 메모리에서 재사용된 값일 수 있음)
ex. torch.empty(size=(4,)): 길이가 4인 1차원 tensor 생성(초기화 하지 않으므로 tensor 안에 들어 있는 값은 무작위로 결정됨)

<code>
torch.empty_like(input)
</code>
: input과 동일한 크기 및 데이터 타입을 가진 tensor를 생성(초기화 하지 않으므로 tensor 안에 들어 있는 값은 무작위로 결정됨)(input과는 다른 새로운 tensor임)
</pre>

<pre>
<code>
torch.eye(n)
</code>
: nxn 크기의 단위 행렬(identity matrix) 생성
** 단위 행렬이란? 대각선 요소가 1이고, 나머지 요소가 0인 정사각형 행렬 **
</pre>

# d_tensor_initialization_random_values.py

In [14]:
import torch

In [16]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([[0.7419, 0.5923, 0.2908]])
tensor([[ 9.2270, 10.0961],
        [ 9.4067,  9.5878],
        [10.0763, 11.1161]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################


<pre>
<code>
torch.randint(low, high, size)
</code>
주어진 범위 내에서 임의의 정수값을 가지는 tensor 생성
- low: 범위의 최솟값 (포함)
- high: 범위의 최댓값 (미포함)
- size: 해당 크기의 tensor 생성
</pre>

<pre>
<code>
torch.rand(size)
</code>
0과 1 사이에서 균등 분포로 무작위 실수값을 가지는 tensor 생성
</pre>

<pre>
<code>
torch.randn(size)
</code>
평균 0, 표준편차 1의 정규분포에서 무작위 값을 가지는 tensor 생성
</pre>

<pre>
<code>
torch.normal(mean, std, size)
</code>
지정된 평균(mean)과 표준편차(std)를 가지는 정규분포에서 무작위 값을 가지는 tensor 생성
</pre>

<pre>
<code>
torch.linspace(start, end, steps)
</code>
지정된 구간(start ~ end)에서 균등 간격으로 나누어진 값을 가지는 tensor 생성
</pre>

<pre>
<code>
torch.arange(stard, end, steps)
</code>
주어진 구간[start)에서 등차 수열로 값을 가지는 tensor 생성
- start: 시작 값(기본값은 0), 포함
- end: 끝 값, 미포함
- steps: 각 값 사이의 간격(기본값은 1)
</pre>

In [17]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


<pre>
<code>
torch.manual_seed(seed)
</code>
랜덤 수 생성기의 시드를 설정함
** 같은 시드를 사용할 경우 항상 동일한 무작위 수가 생성됨 **
=> 시드가 고정되면 동일한 시드와 동일한 무작위 함수 호출 순서에서 항상 동일한 값을 생성함!


# e_tenser_type_conversion.py

In [18]:
import torch

In [20]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[11.6692, 18.3283,  0.2118],
        [18.4972,  9.8370,  3.8937]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


<pre>
<code>
b.to(torch.int32)
</code>
tensor b의 데이터 타입을 torch.int32 타입으로 변환함
+ 뿐만 아니라 디바이스 변환도 가능함

In [21]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64
torch.int16
torch.float64


# f_tenser_operations.py

In [22]:
import torch

In [23]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


- Pytorch의 sub(), mul(), div()은 python 연산자 -, *, /와 동일하게 작동됨

# g_tensor_operations_mm.py

In [24]:
import torch

In [25]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[-4.9983, -1.9715],
        [-2.0698,  0.6196]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


<pre>
<code>
torch.dot()
</code>
두 tensor 간의 내적(dot product) 계산
=> 출력은 스칼라 값이므로 size()는 torch.Size([]) 반환
ex. t1 = torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1])) => 내적 계산: (2 * 2) + (3 * 1) = 4 + 3 = 7
</pre>

<pre>
<code>
torch.mm()
</code>
두 tensor 간의 행렬 곱셈(matrix multiplication) 수행
</pre>

<pre>
<code>
torch.bmm()
</code>
두 배치(batch) 행렬 간의 배치 행렬 곱셈(batch matrix multiplication) 수행
3D tensor를 입력으로 받아, 여러 개의 2D 행렬을 동시에 곱셈할 수 있음
</pre>


# h_tensor_operations_matmul.py

In [26]:
import torch

In [27]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


<pre>
<code>
torch.matmul()
</code>
행렬 곱셈(matrix multiplication)을 수행하는 함수
- tensor, matrix, batch matrix(여러 개의 matrix, [batch_size, 행, 열])을 입력으로 받아 다양한 곱셈 방식을 자동으로 처리함

# i_tensor_broadcasting.py

In [28]:
import torch

In [29]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

- 브로드캐스팅(broadcasting): Pytorch와 Numpy에서 서로 다른 크기의 배열이나 tensor 간의 연산을 가능하게 해주는 기능(크기가 작은 tensor를 자동으로 큰 tensor의 크기에 맞추어 확장하여 연산을 수행할 수 있도록 함)
    - 규칙
        - 차원이 맞지 않으면, 작은 차원의 tensor는 더 큰 차원에 맞도록 자동으로 확장됨
        - 크기가 1인 차원은 확장 가능함
            - 1은 다른 값으로 확장될 수 있는 유일한 값
        - 모든 차원이 동일하거나 한 쪽 차원이 1이면 broadcasting이 가능함
            - 두 tensor의 차원 수가 다르면 작은 쪽 tensor의 앞쪽에 1을 추가하여 차원을 맞춤 -> 그 후 각 차원의 크기가 맞는지 확인

# j_tensor_indexing_slicing.py

In [30]:
import torch

In [31]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
                # [행, 열]
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

In [1]:
import torch

In [2]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


<pre>
<code>view()</code>
    - PyTorch에서 tensor의 크기를 변경할 때 사용하는 함수
    - tensor의 메모리 연속성을 유치한 채로 모양을 변경함
    - ** 메모리에서 tensor의 값이 연속적으로 저장되어 있을 때만 작동 **

<code>reshape()</code>
    - PyTorch에서 tensor의 크기를 변경할 때 사용하는 함수
    - 메모리 연속성을 필요로 하지 않음
        - 연속적으로 저장되어 있지 않은 경우, 내부적으로 메모리 재배치를 수행하여 tensor의 모양을 변경함
        - ex. 전치(transpose)된 tensor에 대해서도 reshape() 사용 가능
</pre>

In [6]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


<pre>
<code>
torch.squeeze(input, dim=None)
</code>
tensor에서 크기가 1인 차원을 제거하는 함수
- input: 입력 tensor
- dim: 제거할 특정 차원(기본적으로 1)
</pre>

<pre>
<code>
torch.unsqueeze(input, dim)
</code>
지정된 위치에 크기가 1인 새 차원을 추가하는 함수
- input: 입력 tensor
- dim: 새 차원을 삽입할 위치

In [7]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


<pre>
<code>
torch.flatten(input, start_dim=0, end_dim=-1)
</code>
tensor의 연속된 차원들을 하나의 차원으로 평탄화(flatten)하는 데 사용되는 함수
(주로 다차원 tensor를 1차원 또는 2차원으로 변환할 때 사용됨, 다른 차원들은 그대로 유지됨)
(tensor의 형태를 변경하지만 데이터 자체는 변경하지 않음)
- input: 평탄화할 입력 tensor
- start_dim: 평탄화를 시작할 차원(기본적으로 1)
- end_dim: 평탄화를 끝낼 차원(기본적으로 -1, 즉 마지막 차원)

In [8]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


<pre>
<code>
tensor.permute(*dims)
</code>
tensor의 차원을 임의의 순서로 재배열함
- 모든 차원을 자유롭게 재배열할 수 있음
- 새로운 순서를 완전히 지정해야 함
</pre>

<pre>
<code>
tensor.transpose(dim0, dim1)
</code>
지정된 두 차원의 순서를 바꿈
- 두 차원만 교환할 수 있음
- 다차원 tensor에서 특정 두 차원만 바꾸고 싶을 때 유용함
</pre>

<pre>
<code>
tensor.t()
</code>
2D tensor(matrix)의 전치(transpose)를 수행하는 함수
- 2D tensor에서만 사용가능
- 행과 열을 교환함
- <code>transpose(0, 1)</code>과 동일한 효과를 가짐
</pre>

# l_tensor_concat.py

In [9]:
import torch

In [10]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

<pre>
<code>
torch.arange(start=0, end, step=1, dtype=None, device=None)
</code>
지정된 간격 내에서 균일하게 분포된 1차원 tensor를 생성하는 함수
- start: 시작값
- end: 끝값
- step: 간격
- dtype: 생성될 tensor의 데이터 타입
- device: tensor가 저장될 장치 (cpu or gpu)
</pre>

<pre>
<code>
torch.cat(tensors, dim=0, out=None)
</code>
주어진 차원을 따라 tensor들을 연결함
(연결되는 tensor들은 연결 차원을 제외한 다른 모든 차원에서 같은 크기여야 함)
- tensors: 연결할 tensor들의 시퀀스 또는 리스트
- dim: tensor를 연결할 차원
- out: 결과를 저장할 출력 tensor
</pre>

# m_tensor_stacking.py

In [11]:
import torch

In [12]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


<pre>
<code>
torch.stack(tensors, dim=0)
</code>
주어진 tensor들을 새로운 차원을 따라 쌓아서 하나의 tensor로 결합하는 함수
- tensors: 쌓을 tensor들의 시퀀스 또는 리스트
- dim: 새로운 차원을 삽입할 위치
- 특징
    - 모든 입력 tensor는 같은 크기와 형태를 가져야 함
    - 결과 tensor는 입력 tensor들보다 한 차원 더 높음
    - 새로운 차원의 크기는 입력 tensor의 개수와 같음
</pre>

<pre>
<code>stack()</code>와 <code>cat()</code>의 차이점
- <code>stack()</code>: 새로운 차원을 만들어 tensor들을 결합
- <code>cat()</code>: 기존 차원을 따라 tensor들을 연결
</pre>


# n_tensor_vstack_hstack.py

In [13]:
import torch

In [14]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# hw1_1.ipynb 후기

- 딥러닝에 입문한 뒤로 PyTorch의 다양한 함수를 이렇게 다양한 예제를 통해 다뤄본 건 이번에 처음인데, 예시와 함께 보면서 코드를 돌려보니 어떻게 동작하는지 알 수 있어서 좋았음.
- 그냥 동작하고 끝이 아니라 함수가 어떻게 생겼는지 직접 찾아보고 기록하면서 진행하니 더욱 더 머릿속에 잘 남고 이해가 잘 되는 것 같음.
- 2차원까지는 머릿속에 어떻게든 그려서 바로 이해할 수 있었는데 차원이 커질수록 그리기가 어려워 이해하는 데 시간이 조금 걸렸음.